test_static: test_static.c matrix_static.c
	g++ -std=c++17 test_static.c matrix_static.c -o output_static


test_dynamic: test_dynamic.c matrix_dynamic.c
	g++ -std=c++17 test_dynamic.c matrix_dynamic.c -o output_dynamic

